[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kingfisher"
description = "Download/extract biological FASTA/Q read data and metadata"
readme = "README.md"
requires-python = ">=3.7"
license = "GPL-3.0-or-later"
authors = [{ name = "Ben Woodcroft" }]
keywords = ["bioinformatics", "metagenomics", "SRA", "ENA"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Programming Language :: Python :: 3"
]
version = "0.5.0"
dependencies = [
    "extern",
    "requests",
    "tqdm",
    "pandas",
    "bird-tool-utils",
    "pyarrow",
]

[project.urls]
Homepage = "https://github.com/wwood/kingfisher-download"

[project.scripts]
kingfisher = "kingfisher.cli:main"

[tool.setuptools]
packages = ["kingfisher"]
include-package-data = true
