#!/usr/bin/env python3

"""Build dependency definition files from pixi.toml and pixi.lock.

Generates:
  - admin/environment.yml (conda pinned dependencies)
  - admin/requirements.txt (pip pinned dependencies)
  - Updates pyproject.toml dependencies list

Only reads pixi.toml and pixi.lock — requires PyYAML but not a working pixi
environment with kingfisher installed.
"""

import re
import os
import tomllib
import yaml

base_dir = os.path.join(os.path.dirname(__file__), "..")

# Load pixi.toml
with open(os.path.join(base_dir, "pixi.toml"), "rb") as f:
    pixi_data = tomllib.load(f)

# Load pixi.lock
with open(os.path.join(base_dir, "pixi.lock"), "rb") as f:
    lock_data = yaml.safe_load(f)

# Gather explicitly declared conda dependencies from pixi.toml
declared_conda = set()
for section in ["dependencies", ["feature", "main", "dependencies"]]:
    if isinstance(section, list):
        d = pixi_data
        for subsec in section:
            d = d.get(subsec, {})
    else:
        d = pixi_data.get(section, {})
    for pkg in d:
        declared_conda.add(pkg.lower())

print(f"Found {len(declared_conda)} declared conda dependencies in pixi.toml.")

# Extract conda package name+version from pixi.lock packages list.
# Conda URLs look like: .../aria2-1.37.0-h4e1c2bf_3.conda or .../extern-0.4.1-py_0.tar.bz2
# Format: {name}-{version}-{build}.{ext}
conda_versions = {}
for pkg_entry in lock_data.get("packages", []):
    if not isinstance(pkg_entry, dict):
        continue
    url = pkg_entry.get("conda")
    if not url:
        continue
    # Get filename from URL, strip extensions
    filename = url.rsplit("/", 1)[-1]
    for ext in (".conda", ".tar.bz2"):
        if filename.endswith(ext):
            filename = filename[:-len(ext)]
            break
    # Split into name-version-build: last two segments are build and version
    parts = filename.rsplit("-", 2)
    if len(parts) == 3:
        name, version, _build = parts
        conda_versions[name.lower()] = version

# Build environment.yml
conda_deps = sorted(
    f"{pkg}={conda_versions[pkg]}"
    for pkg in declared_conda
    if pkg in conda_versions
)
env_data = {
    "channels": ["conda-forge", "bioconda"],
    "dependencies": conda_deps,
}
with open(os.path.join(base_dir, "admin", "environment.yml"), "w") as f:
    f.write("# This file was autogenerated by build_dep_defs_from_pixi.py - do not change manually.\n")
    yaml.dump(env_data, f, default_flow_style=False)
print(f"environment.yml written with {len(conda_deps)} dependencies.")

# Build requirements.txt from pinned conda versions of PyPI-relevant packages.
project_name = pixi_data.get("workspace", {}).get("name", "").lower()

# Conda package names sometimes differ from pip names.
CONDA_TO_PIP = {
    "bird_tool_utils_python": "bird_tool_utils",
}
# Packages that are not Python libraries (skip for requirements.txt)
NON_PIP_PACKAGES = {
    "python", "pigz", "curl", "aria2", "sra-tools", "sracat", "aspera-cli", "awscli",
}

pip_count = 0
with open(os.path.join(base_dir, "admin", "requirements.txt"), "w") as f:
    f.write("# This file was autogenerated by build_dep_defs_from_pixi.py - do not change manually.\n")
    for pkg in sorted(declared_conda):
        if pkg == project_name or pkg in NON_PIP_PACKAGES:
            continue
        pip_name = CONDA_TO_PIP.get(pkg, pkg)
        version = conda_versions.get(pkg, "")
        if version and version != "0.0.0":
            f.write(f"{pip_name}=={version}\n")
        else:
            f.write(f"{pip_name}\n")
        pip_count += 1
print(f"requirements.txt written with {pip_count} dependencies.")

# Update pyproject.toml dependencies from the editable install's requires_dist
# in pixi.lock (these are the unpinned dependency names).
pypi_requires = []
for pkg_entry in lock_data.get("packages", []):
    if not isinstance(pkg_entry, dict):
        continue
    if "pypi" in pkg_entry and pkg_entry.get("name", "").lower() == project_name:
        pypi_requires = pkg_entry.get("requires_dist", [])
        break

if pypi_requires:
    deps_lines = ",\n".join(f'    "{dep}"' for dep in pypi_requires)
    deps_block = f"[\n{deps_lines},\n]"

    pyproject_path = os.path.join(base_dir, "pyproject.toml")
    with open(pyproject_path) as f:
        content = f.read()
    content = re.sub(
        r'dependencies = \[.*?\]',
        f'dependencies = {deps_block}',
        content,
        count=1,
        flags=re.DOTALL,
    )
    with open(pyproject_path, "w") as f:
        f.write(content)
    print(f"pyproject.toml dependencies updated: {pypi_requires}")
else:
    print("WARNING: Could not find pypi requires_dist in pixi.lock")
