name: Current Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pixi_test_dependencies_locked:
    name: Pixi test_dependencies_locked ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v3

      - name: Install Pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Show environment info
        run: |
          pixi run -e dev --frozen pixi info
          pixi run -e dev --frozen pixi list

      - name: Install ascp
        run: |
          pixi run -e dev --frozen ascli config ascp install
          echo "Checking ascp installation"
          find ~/.aspera -name ascp

      - name: Run tests with Pixi
        run: |
          pixi run -e dev --frozen pytest test -v --timeout=300 --timeout-method=signal -m "not flaky"

  # Run after removing lock file so dependences are unlocked
  pixi_test_dependencies_optimistic:
    name: Pixi test_dependencies_optimistic ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v3

      - name: Install Pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Remove lock file
        run: |
          rm -fv pixi.lock admin/requirements.txt admin/environment.yml
          mkdir -p admin
          touch admin/requirements.txt

      - name: Create dev environment
        run: |
          pixi run -e dev pixi info

      - name: Show environment info
        run: |
          pixi run -e dev pixi list

      - name: Install ascp
        run: |
          pixi run -e dev --frozen ascli config ascp install
          echo "Checking ascp installation"
          find ~/.aspera -name ascp

      - name: Run tests with Pixi
        run: |
          pixi run -e dev pytest test -v --timeout=300 --timeout-method=signal -m "not flaky"
